### ISSUE TITLE
Replace external link to polyfill.io

### ISSUE THREAD

**Issue by skinread** [atomicojs/docs#6]
https://github.com/atomicojs/docs/blob/eebf9e0c58af323d06df18599979cdc8033b8654/guides/frequent-questions/page.md?plain=1#L17

Thanks for the Atomico library. I noticed this link in the docs to pollyfill.io which may have been [compromised](https://polykill.io/) earlier this year.

Possibly can be replaced with a mirror such as https://polyfill-fastly.io/ or https://cdnjs.cloudflare.com/polyfill/

**Comment by UpperCod** [comment]
Hi @skinread, thank you for sharing this. Following your recommendation, I have added polyfill-fastly for the use of polyfills.
